# Generated by Django 5.2.9 on 2025-12-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50)),
                ('request_date', models.DateField()),
                ('requester_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('design_start_date', models.DateField()),
                ('design_end_date', models.DateField()),
                ('assigned_to', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
